name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update APT database
      run: sudo apt update
    - name: Install libsdl2-dev
      run: sudo apt-get install libsdl2-dev gcc make
    - name: make
      run: make
